blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

#! Urls patterns of the blog app

app_name = "blog"

urlpatterns = [
    path(
        "",
        views.post_list,
        name="post_list",
    ),
    path(
        "<int:post_id>/share/",
        views.share_post,
        name="post_share",
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path(
        "tag/<slug:tag_slug>/",
        views.post_list,
        name="post_list_by_tag",
    ),
    path(
        "feed/",
        LatestPostsFeed(),
        name="post_feed",
    ),
    path(
        "search/",
        views.post_search,
        name="search",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager


# Create your models here.
class PublihsedManager(models.Manager):
    def get_queryset(self):
        return super(PublihsedManager, self).get_queryset().filter(status="published")


class Post(models.Model):
    STATUST_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_post")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        choices=STATUST_CHOICES,
        default="draft",
    )
    tags = TaggableManager()

    class Meta:
        ordering = ("-publish",)

    def __str__(
        self,
    ):
        return self.title

    # Custom  and default managers
    objects = models.Manager()
    published = PublihsedManager()

    # canonical url

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ],
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField(max_length=254)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"comment by {self.name} on { self.post}"

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(
        label="",
        max_length=64,
        widget=forms.TextInput(attrs={"placeholder": "Enter your name"}),
    )
    email = forms.EmailField(
        label="",
        widget=forms.EmailInput(
            attrs={"placeholder": "Enter your email"},
        ),
    )
    to = forms.EmailField(
        label="",
        widget=forms.EmailInput(
            attrs={"placeholder": "Enter the reveiver email"},
        ),
    )
    comments = forms.CharField(
        label="",
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "Enter the comment"}),
    )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "Enter your name"}),
            "email": forms.EmailInput(
                attrs={"placeholder": "Enter your email"},
            ),
        }
        labels = {
            "name": "",
            "email": "",
            "body": "",
        }
        help_texts = {
            "name": "",
            "email": "",
            "body": "",
        }
        error_messages = {
            "name": "",
            "email": "",
            "body": "",
        }
        field_classes = {
            "name": forms.CharField,
            "email": forms.EmailField,
            "body": forms.CharField,
        }


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.conf import settings
from django.db.models import Count
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

# Create your views here.


# ! This method return all the post with published status
# def post_list(request):
#     posts = Post.published.all()
#     context = {"posts": posts}
#     return render(
#         request,
#         "blog/post/list.html",
#         context,
#     )


# ! this is pagination page


def post_list(request, tag_slug=None):
    object_lists = Post.published.all()
    tags = Tag.objects.all().distinct()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_lists = object_lists.filter(tags__in=[tag])
    paginator = Paginator(object_lists, 4)
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of the range
        posts = paginator.page(paginator.num_pages)

    context = {
        "posts": posts,
        "page": page,
        "tag": tag,
        "tags": tags,
    }
    return render(
        request,
        "blog/post/list.html",
        context,
    )


# ! This method return single post
# def post_detail(request, year, month, day, post):
#     post = get_object_or_404(
#         Post,
#         slug=post,
#         status="published",
#         publish__year=year,
#         publish__month=month,
#         publish__day=day,
#     )
#     context = {"post": post}

#     return render(
#         request,
#         "blog/post/detail.html",
#         context,
#     )


# ! This method return single post
def post_detail(request, year, month, day, post):
    post = Post.published.get(
        slug=post,
        status="published",
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            print(post)
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]
    context = {
        "post": post,
        "comments": comments,
        "new_comment": new_comment,
        "comment_form": comment_form,
        "similar_posts": similar_posts,
    }
    return render(
        request,
        "blog/post/detail.html",
        context,
    )


# ! Share post with friends


def share_post(request, post_id):
    # retrieve respective post

    post = get_object_or_404(Post, id=post_id, status="published")

    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # form fields passed validation
            cleand_data = form.cleaned_data
            print(cleand_data)
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cleand_data['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cleand_data['comments']}"
            send_mail(
                subject,
                message,
                "fatihamtech@gmail.com",
                [cleand_data.get("to")],
                fail_silently=False,
            )
            return render(
                request,
                "blog/post/share.html",
                {"form": form, "success": True},
            )
    else:
        form = EmailPostForm()
        context = {
            "form": form,
            "post": post,
        }
    return render(
        request,
        "blog/post/share.html",
        context,
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]

            #! First results only with query
            # results = Post.published.annotate(
            #     search=SearchVector("title", "body")
            # ).filter(search=query)

            #! Second results with stemming and ranking
            search_vector = SearchVector("title", "body")
            search_query = SearchQuery(query)
            results = (
                Post.published.annotate(
                    search=search_vector, rank=SearchRank(search_vector, search_query)
                )
                .filter(search=search_query)
                .order_by(("-rank"))
            )
    context = {
        "form": form,
        "query": query,
        "results": results,
    }
    return render(request, "blog/post/search.html", context=context)

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %} {% load blog_tags %} {% load static %} {% block title %}
FatiBlog{%endblock title %} {% block content %}
<div class="container details">
  <p class="date">Published {{post.publish}} by {{post.author}}</p>
  <p>{{post.body|markdown}}</p>


{% with comments.count as total_comments %}
<h2>{{ total_comments }} comment{{total_comments|pluralize}}</h2>
{% endwith %}

{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{forloop.counter}} by {{comment.name}}
        {{comment.created}}
    </p>
    {{comment.body}}
    
</div>
{%empty%}
<p>There are no comments yet</p>
{% endfor %}

{% if new_comment %}

<h2>Your comment has been added successfully</h2>
{% else %}
<h2>Add new comment</h2>
<form action="" method="post">
    {% csrf_token %}
    {{comment_form}}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}
<p><a href="{% url "blog:post_share" post.id %}">Share this post</a></p>


<h2>Similar posts</h2>
{% for post in similar_posts %}
<p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
{%empty%}
<p>There are no similar posts yet</p>
{% endfor %}
{% endblock content %}
</div>

blog/templates/blog/post/latest_post.html
<ul>
  {% for post in latest_posts %}
  <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %} {% load static %} {% block title %}
FatiBlog{%endblock title %} {% block content %}
<div class="container">
  <p class="tags">
    {% for tag in tags %}
    <a href="{% url 'blog:post_list_by_tag' tag.slug%}">{{tag.name}}</a>
    {%endfor %}
  </p>
  {% if tag %}
  <h2>posts tagged with {{tag.name}}</h2>
  {% endif %} {% for post in posts %}
  <h2>
    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
  </h2>

  <p class="date">Published {{post.publish}} by {{post.author}}</p>
  <p>{{post.body|truncatewords:30|linebreaks}}</p>
  {% endfor %}
</div>
{% include "./pagination.html"%} {% endblock content %}

blog/templates/blog/post/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if posts.has_previous %}
    <a href="?page={{posts.previous_page_number}}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{posts.number}} of {{posts.paginator.num_pages}}.</span
    >
    {% if posts.has_next %}
    <a href="?page={{posts.next_page_number}}">Next</a>{% endif %}
  </span>
</div>

blog/templates/blog/post/search.html
{% extends "blog/base.html" %} {% load static %} {% block title %}
FatiBlog{%endblock title %} {% block content %} {% if query %}
<h1>Post containing "{{query}}"</h1>
<h3>
  {% with results.count as total_count %} Found {{total_count}}
  result{{total_count|pluralize}} {% endwith %}
</h3>
{% for post in results %}
<p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
{%empty%}
<p>There are no results found</p>
{% endfor %}
<p><a href="{% url 'blog:search' %}">Search again</a></p>
{% else %}
<h1>Search posts</h1>

<form action="" method="get">
  {{form.as_p}}
  <input type="submit" value="search" />
</form>
{% endif %} {% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %} {% block title %} share post{% endblock title %}
{% block content %} {% if success %}
<h1>Email successfully sent</h1>
<p>"{{post.post.title}}" was successfully sent to {{form.cleaned_data.to}}</p>
{% else %}
<h1>Share "{{post.title}}" by e-mail</h1>

<form action="" method="post">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Send" />
</form>
{% endif %} {% endblock content %}

blog/templates/blog/post/sidebar.html
<div class="side-bar">
  <h2>My blog</h2>
  <p>Total blogs {%total_posts%}</p>
  <p>
    <a href="{%url 'blog:post_feed'%}"> Subcribe to my RSS feed</a>
  </p>
  <div class="latest_posts">
    <h3>Latest posts</h3>
    {% show_latest_posts 3 %}
  </div>

  <div class="most-commented">
    <h3>Most commented posts</h3>
    {% most_commented_posts as most_commented_posts %} {% for post in
    most_commented_posts %}
    <li>
      <a href="{{post.get_absolute_url}}">{{post.title}}</a>
    </li>
    {% endfor %}
  </div>
</div>